__title__ = "duro"
__version__ = "0.1.0"
__description__ = "A customizable kanban board for the terminal."
__url__ = "https://github.com/kmccullen97/duro"
__author__ = "Kyle McCullen"
__author_email__ = "kmccullen@protonmail.com"
__license__ = "MIT License"
