active: bold
colors:
  active_card:
  - cyan
  - 0
  - 0
  active_list:
  - cyan
  - 0
  - 0
  date:
  - yellow
  - 0
  - 0
  default:
  - white
  - 0
  - 0
  footer:
  - white
  - magenta
  - 0
  id:
  - cyan
  - 0
  - 0
  none:
  - yellow
  - 0
  - 0
data_file: path/to/data/file
date_format: '%b %d, %Y %I:%M %p'
min_list_width: 50
